apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-restapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-restapi
    spec:
      containers:
      - name: nodejs-restapi
        image: registry.gitlab.com/madhavikhatawakar/nodejs-rest-api
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: registry.gitlab.com
